export const QUERY_KEYS = {
  clients:              ['clients'],
  clientsGlobal:        (q) => ['clients', 'global', q],
  client:               (id) => ['clients', id],
  commandes:            ['commandes'],
  commande:             (id) => ['commandes', id],
  commandeStats:        ['commandes', 'stats'],
  commandeItems:        (id) => ['commandes', id, 'items'],
  commandeEcheances:    (id) => ['commandes', id, 'echeances'],
  commandeGroupes:      ['commande-groupes'],
  commandeGroupe:       (id) => ['commande-groupes', id],
  mesures:              (clientId) => ['mesures', clientId],
  vetements:            ['vetements'],
  abonnement:           ['abonnement'],
  libellesPlans:        ['plans', 'libelles'],
  abonnementHistory:    ['abonnement', 'historique'],
  paiements:            ['paiements'],
  equipe:               ['equipe'],
  points:               ['points'],
  pointsHistory:        ['points', 'historique'],
  notifications:        ['notifications'],
  infos:              ['infos'],
  infosCount:         ['infos', 'count'],
  notificationsCount:   ['notifications', 'count'],
  quota:                ['quota'],
  tickets:              ['tickets'],
  mesAteliers:          ['ateliers', 'mes-ateliers'],
  atelierStats:         (id) => ['ateliers', id, 'stats'],
  archives:             ['archives'],
  caisseStats:          (mois) => ['caisse', 'stats', mois],
  caisseClients:        ['caisse', 'clients'],
  galerie:              ['galerie'],
  galerieQuota:         ['galerie', 'quota'],
  dashboard:            ['dashboard'],
}
