export const QUERY_KEYS = {
  clients:            ['clients'],
  client:             (id) => ['clients', id],
  commandes:          ['commandes'],
  commande:           (id) => ['commandes', id],
  commandeStats:      ['commandes', 'stats'],
  mesures:            (clientId) => ['mesures', clientId],
  vetements:          ['vetements'],
  abonnement:         ['abonnement'],
  abonnementHistory:  ['abonnement', 'historique'],
  paiements:          ['paiements'],
  equipe:             ['equipe'],
  points:             ['points'],
  pointsHistory:      ['points', 'historique'],
  notifications:      ['notifications'],
  notificationsCount: ['notifications', 'count'],
  quota:              ['quota'],
  tickets:            ['tickets'],
  mesAteliers:        ['ateliers', 'mes-ateliers'],
  atelierStats:       (id) => ['ateliers', id, 'stats'],
  archives:           ['archives'],
  caisseStats:        (mois) => ['caisse', 'stats', mois],
  caisseClients:      ['caisse', 'clients'],
}
