import { appSchema, tableSchema } from '@nozbe/watermelondb'

export default appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'clients',
      columns: [
        { name: 'nom',            type: 'string' },
        { name: 'prenom',         type: 'string', isOptional: true },
        { name: 'telephone',      type: 'string' },
        { name: 'type_profil',    type: 'string' },
        { name: 'avatar_index',   type: 'number', isOptional: true },
        { name: 'is_vip',         type: 'boolean' },
        { name: 'is_archived',    type: 'boolean' },
        { name: 'notes',          type: 'string', isOptional: true },
        { name: 'atelier_id',     type: 'string' },
        { name: 'created_by',     type: 'string', isOptional: true },
        { name: 'synced_at',      type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'commandes',
      columns: [
        { name: 'client_id',                type: 'string' },
        { name: 'vetement_id',              type: 'string', isOptional: true },
        { name: 'client_nom',               type: 'string', isOptional: true },
        { name: 'vetement_nom',             type: 'string', isOptional: true },
        { name: 'quantite',                 type: 'number', isOptional: true },
        { name: 'prix',                     type: 'number' },
        { name: 'acompte',                  type: 'number', isOptional: true },
        { name: 'mode_paiement_acompte',    type: 'string', isOptional: true },
        { name: 'statut',                   type: 'string' },
        { name: 'description',              type: 'string', isOptional: true },
        { name: 'note_interne',             type: 'string', isOptional: true },
        { name: 'date_livraison_prevue',    type: 'string', isOptional: true },
        { name: 'date_livraison_effective', type: 'string', isOptional: true },
        { name: 'urgence',                  type: 'boolean' },
        { name: 'is_archived',              type: 'boolean' },
        { name: 'rappel_j2_envoye',         type: 'boolean' },
        { name: 'photo_tissu_url',          type: 'string', isOptional: true },
        { name: 'atelier_id',               type: 'string' },
        { name: 'synced_at',                type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'mesures',
      columns: [
        { name: 'client_id',   type: 'string' },
        { name: 'vetement_id', type: 'string', isOptional: true },
        { name: 'champs_json', type: 'string' },
        { name: 'is_archived', type: 'boolean' },
        { name: 'atelier_id',  type: 'string' },
        { name: 'synced_at',   type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'vetements',
      columns: [
        { name: 'nom',                  type: 'string' },
        { name: 'categorie',            type: 'string', isOptional: true },
        { name: 'description',          type: 'string', isOptional: true },
        { name: 'libelles_mesures_json',type: 'string', isOptional: true },
        { name: 'images_json',          type: 'string', isOptional: true },
        { name: 'image_url',            type: 'string', isOptional: true },
        { name: 'est_gabarit',          type: 'boolean' },
        { name: 'is_systeme',           type: 'boolean' },
        { name: 'is_archived',          type: 'boolean' },
        { name: 'template_numero',      type: 'number', isOptional: true },
        { name: 'atelier_id',           type: 'string' },
        { name: 'synced_at',            type: 'number', isOptional: true },
      ],
    }),
  ],
})
