export { default as DashboardPage }     from './DashboardPage'
export { default as CataloguePage }     from './CataloguePage'
export { default as EquipePage }        from './EquipePage'
export { default as PointsPage }        from './PointsPage'
export { default as NotificationsPage } from './NotificationsPage'
export { default as ParametresPage }     from './ParametresPage'
export { default as CommunicationsPage } from './CommunicationsPage'
export * from './auth'
export * from './clients'
export * from './commandes'
