export const mockNotifications = [
  {
    id: 1,
    type: 'commande',
    titre: 'Commande à livrer bientôt',
    message: 'La commande #7 de Aicha Touré est prévue pour le 28 avril. Pensez à la préparer.',
    lu: false,
    created_at: '2026-04-22T08:00:00Z',
    meta: { commande_id: 7 },
  },
  {
    id: 2,
    type: 'commande',
    titre: 'Essayage demain',
    message: "Essayage de Fatou Diallo prévu pour demain — pensez à confirmer le rendez-vous.",
    lu: false,
    created_at: '2026-04-22T09:00:00Z',
    meta: { commande_id: 2 },
  },
  {
    id: 3,
    type: 'commande',
    titre: 'Nouvelle commande ajoutée',
    message: 'La commande de Bintou Camara a été créée avec succès.',
    lu: false,
    created_at: '2026-04-19T13:05:00Z',
    meta: { commande_id: 8 },
  },
  {
    id: 4,
    type: 'paiement',
    titre: 'Avance reçue',
    message: 'Avance de 30 000 XOF reçue pour la commande #1 de Rokhaya Mbaye.',
    lu: true,
    created_at: '2026-04-05T09:10:00Z',
    meta: { commande_id: 1 },
  },
  {
    id: 5,
    type: 'abonnement',
    titre: 'Abonnement Pro actif',
    message: "Votre abonnement Pro est actif jusqu'au 31 décembre 2026.",
    lu: true,
    created_at: '2026-04-01T10:00:00Z',
    meta: {},
  },
  {
    id: 6,
    type: 'systeme',
    titre: 'Bienvenue sur Couture Pro',
    message: "Votre atelier est configuré. Commencez par ajouter vos clients et vos premières commandes.",
    lu: true,
    created_at: '2025-01-15T08:30:00Z',
    meta: {},
  },
]
