export const ADMIN_KEYS = {
  me:           ['admin', 'me'],
  ateliers:     ['admin', 'ateliers'],
  atelier:      (id) => ['admin', 'ateliers', id],
  atelierFid:   (id) => ['admin', 'ateliers', id, 'fidelite'],
  plans:        ['admin', 'plans'],
  plan:         (id) => ['admin', 'plans', id],
  transactions: ['admin', 'transactions'],
  paiements:    ['admin', 'paiements'],
  tickets:      ['admin', 'tickets'],
  ticket:       (id) => ['admin', 'tickets', id],
  offres:       ['admin', 'offres'],
  listeNoire:       ['admin', 'liste-noire'],
  signalements:     ['admin', 'signalements'],
  banniere:         ['admin', 'banniere'],
  sponsorisation:   ['admin', 'sponsorisation'],
  audit:            ['admin', 'audit'],
  admins:           ['admin', 'admins'],
  sousAteliers:     (id) => ['admin', 'ateliers', id, 'sous-ateliers'],
  splashThemes:     ['admin', 'splash-themes'],
  identiteLegale:   ['admin', 'identite-legale'],
  moderationAvis:   ['admin', 'moderation-avis'],
  compteRebours:    ['admin', 'compte-a-rebours'],
  journalMaj:       ['admin', 'journal-maj'],
  analytique:       ['admin', 'analytique'],
}
